version: '3.8'

services: 
  goo_pars_backend:
    build: ./goo_pars_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./goo_pars_backend/:/usr/src/goo_pars_backend/
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    
    depends_on:
      - db

  db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgres/data/
      environment:
        - POSTGRES_USER=django_user
        - POSTGRES_PASSWORD=qwerty12345
        - POSTGRES_DB=for_django_test

  frontend_main:
    build: ./frontend_main
    container_name: frontend_main_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  postgres_data: