# Generated by Django 4.0.5 on 2022-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("order_number", models.IntegerField(max_length=7, unique=True)),
                ("price_usd", models.IntegerField()),
                ("date_ship", models.DateTimeField()),
                ("price_rub", models.IntegerField()),
            ],
        ),
    ]
